# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHBoxLayout, QLabel, QLayout, QLineEdit,
    QMainWindow, QPushButton, QScrollArea, QSizePolicy,
    QSlider, QStatusBar, QTabWidget, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1029, 710)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy1)
        self.scrollArea.setMinimumSize(QSize(351, 100))
        self.scrollArea.setMaximumSize(QSize(351, 671))
        self.scrollArea.setStyleSheet(u"")
        self.scrollArea.setFrameShape(QFrame.Box)
        self.scrollArea.setFrameShadow(QFrame.Plain)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 349, 669))
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.widget = QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(311, 641))
        self.widget.setMaximumSize(QSize(311, 641))
        self.frame_showData = QFrame(self.widget)
        self.frame_showData.setObjectName(u"frame_showData")
        self.frame_showData.setGeometry(QRect(0, 0, 161, 91))
        self.frame_showData.setFrameShape(QFrame.Box)
        self.checkBox_isosurface1 = QCheckBox(self.frame_showData)
        self.checkBox_isosurface1.setObjectName(u"checkBox_isosurface1")
        self.checkBox_isosurface1.setGeometry(QRect(10, 0, 101, 21))
        self.checkBox_isosurface2 = QCheckBox(self.frame_showData)
        self.checkBox_isosurface2.setObjectName(u"checkBox_isosurface2")
        self.checkBox_isosurface2.setGeometry(QRect(10, 20, 101, 21))
        self.frame_saveImage = QFrame(self.widget)
        self.frame_saveImage.setObjectName(u"frame_saveImage")
        self.frame_saveImage.setGeometry(QRect(0, 100, 161, 61))
        self.frame_saveImage.setFrameShape(QFrame.Box)
        self.label_types = QLabel(self.frame_saveImage)
        self.label_types.setObjectName(u"label_types")
        self.label_types.setGeometry(QRect(10, 0, 68, 21))
        self.comboBox_saveType = QComboBox(self.frame_saveImage)
        self.comboBox_saveType.addItem("")
        self.comboBox_saveType.addItem("")
        self.comboBox_saveType.setObjectName(u"comboBox_saveType")
        self.comboBox_saveType.setGeometry(QRect(10, 30, 71, 21))
        self.pushButton_saveImage = QPushButton(self.frame_saveImage)
        self.pushButton_saveImage.setObjectName(u"pushButton_saveImage")
        self.pushButton_saveImage.setGeometry(QRect(90, 20, 61, 31))
        self.frame_axisAndUnits = QFrame(self.widget)
        self.frame_axisAndUnits.setObjectName(u"frame_axisAndUnits")
        self.frame_axisAndUnits.setGeometry(QRect(170, 0, 141, 161))
        self.frame_axisAndUnits.setFrameShape(QFrame.Box)
        self.label_coordinates = QLabel(self.frame_axisAndUnits)
        self.label_coordinates.setObjectName(u"label_coordinates")
        self.label_coordinates.setGeometry(QRect(10, 10, 91, 21))
        self.comboBox_coordinates = QComboBox(self.frame_axisAndUnits)
        self.comboBox_coordinates.addItem("")
        self.comboBox_coordinates.addItem("")
        self.comboBox_coordinates.setObjectName(u"comboBox_coordinates")
        self.comboBox_coordinates.setGeometry(QRect(10, 30, 111, 21))
        self.comboBox_coordinates.setIconSize(QSize(16, 16))
        self.label_axisUnits = QLabel(self.frame_axisAndUnits)
        self.label_axisUnits.setObjectName(u"label_axisUnits")
        self.label_axisUnits.setGeometry(QRect(10, 60, 81, 21))
        self.comboBox_axisUnits = QComboBox(self.frame_axisAndUnits)
        self.comboBox_axisUnits.addItem("")
        self.comboBox_axisUnits.addItem("")
        self.comboBox_axisUnits.setObjectName(u"comboBox_axisUnits")
        self.comboBox_axisUnits.setGeometry(QRect(10, 80, 111, 21))
        self.label_units = QLabel(self.frame_axisAndUnits)
        self.label_units.setObjectName(u"label_units")
        self.label_units.setGeometry(QRect(10, 110, 61, 21))
        self.comboBox_units = QComboBox(self.frame_axisAndUnits)
        self.comboBox_units.addItem("")
        self.comboBox_units.addItem("")
        self.comboBox_units.setObjectName(u"comboBox_units")
        self.comboBox_units.setGeometry(QRect(10, 130, 111, 21))
        self.frame_dataSlider = QFrame(self.widget)
        self.frame_dataSlider.setObjectName(u"frame_dataSlider")
        self.frame_dataSlider.setGeometry(QRect(0, 170, 311, 121))
        font = QFont()
        font.setBold(False)
        self.frame_dataSlider.setFont(font)
        self.frame_dataSlider.setFrameShape(QFrame.Box)
        self.label_firstTime_slider = QLabel(self.frame_dataSlider)
        self.label_firstTime_slider.setObjectName(u"label_firstTime_slider")
        self.label_firstTime_slider.setGeometry(QRect(10, 70, 91, 21))
        self.label_lastTime_slider = QLabel(self.frame_dataSlider)
        self.label_lastTime_slider.setObjectName(u"label_lastTime_slider")
        self.label_lastTime_slider.setGeometry(QRect(200, 70, 101, 21))
        self.horizontalSlider_dataStartTime = QSlider(self.frame_dataSlider)
        self.horizontalSlider_dataStartTime.setObjectName(u"horizontalSlider_dataStartTime")
        self.horizontalSlider_dataStartTime.setGeometry(QRect(20, 90, 251, 20))
        self.horizontalSlider_dataStartTime.setOrientation(Qt.Horizontal)
        self.horizontalSlider_dataStartTime.setTickPosition(QSlider.NoTicks)
        self.horizontalSlider_dataStartTime.setTickInterval(0)
        self.label_startTime_head = QLabel(self.frame_dataSlider)
        self.label_startTime_head.setObjectName(u"label_startTime_head")
        self.label_startTime_head.setGeometry(QRect(10, 0, 91, 31))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.label_startTime_head.setFont(font1)
        self.label_endTime_head = QLabel(self.frame_dataSlider)
        self.label_endTime_head.setObjectName(u"label_endTime_head")
        self.label_endTime_head.setGeometry(QRect(10, 30, 91, 31))
        self.label_endTime_head.setFont(font1)
        self.label_startTime = QLabel(self.frame_dataSlider)
        self.label_startTime.setObjectName(u"label_startTime")
        self.label_startTime.setGeometry(QRect(110, 0, 171, 31))
        self.label_startTime.setFont(font1)
        self.label_endTime = QLabel(self.frame_dataSlider)
        self.label_endTime.setObjectName(u"label_endTime")
        self.label_endTime.setGeometry(QRect(110, 30, 171, 31))
        self.label_endTime.setFont(font1)
        self.tabWidget = QTabWidget(self.widget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 310, 311, 331))
        self.tabWidget.setStyleSheet(u"QTabWidget::pane {\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-top: 1px solid rgb(200, 200, 200);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-bottom-color: #C2C7CB;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-bottom-color: #C2C7CB;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px;\n"
"	border-bottom: 1px solid rgb(0, 0, 0)\n"
"}")
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_slice = QWidget()
        self.tab_slice.setObjectName(u"tab_slice")
        self.label_xy = QLabel(self.tab_slice)
        self.label_xy.setObjectName(u"label_xy")
        self.label_xy.setGeometry(QRect(10, 40, 61, 21))
        self.label_slice = QLabel(self.tab_slice)
        self.label_slice.setObjectName(u"label_slice")
        self.label_slice.setGeometry(QRect(10, 10, 61, 21))
        self.horizontalSlider_xy = QSlider(self.tab_slice)
        self.horizontalSlider_xy.setObjectName(u"horizontalSlider_xy")
        self.horizontalSlider_xy.setGeometry(QRect(20, 80, 181, 21))
        self.horizontalSlider_xy.setOrientation(Qt.Horizontal)
        self.checkBox_xy_contour = QCheckBox(self.tab_slice)
        self.checkBox_xy_contour.setObjectName(u"checkBox_xy_contour")
        self.checkBox_xy_contour.setGeometry(QRect(220, 40, 21, 21))
        font2 = QFont()
        font2.setPointSize(9)
        self.checkBox_xy_contour.setFont(font2)
        self.checkBox_xy_contour.setIconSize(QSize(16, 16))
        self.checkBox_xy_image = QCheckBox(self.tab_slice)
        self.checkBox_xy_image.setObjectName(u"checkBox_xy_image")
        self.checkBox_xy_image.setGeometry(QRect(270, 40, 21, 21))
        self.label_contour = QLabel(self.tab_slice)
        self.label_contour.setObjectName(u"label_contour")
        self.label_contour.setGeometry(QRect(198, 10, 61, 21))
        self.label_image = QLabel(self.tab_slice)
        self.label_image.setObjectName(u"label_image")
        self.label_image.setGeometry(QRect(260, 10, 51, 21))
        self.label_xy_minValue = QLabel(self.tab_slice)
        self.label_xy_minValue.setObjectName(u"label_xy_minValue")
        self.label_xy_minValue.setGeometry(QRect(10, 60, 61, 21))
        self.label_xy_maxValue = QLabel(self.tab_slice)
        self.label_xy_maxValue.setObjectName(u"label_xy_maxValue")
        self.label_xy_maxValue.setGeometry(QRect(160, 60, 61, 21))
        self.checkBox_yz_contour = QCheckBox(self.tab_slice)
        self.checkBox_yz_contour.setObjectName(u"checkBox_yz_contour")
        self.checkBox_yz_contour.setGeometry(QRect(220, 130, 21, 21))
        self.label_yz_minValue = QLabel(self.tab_slice)
        self.label_yz_minValue.setObjectName(u"label_yz_minValue")
        self.label_yz_minValue.setGeometry(QRect(10, 150, 61, 21))
        self.label_yz_maxValue = QLabel(self.tab_slice)
        self.label_yz_maxValue.setObjectName(u"label_yz_maxValue")
        self.label_yz_maxValue.setGeometry(QRect(160, 150, 61, 21))
        self.checkBox_yz_image = QCheckBox(self.tab_slice)
        self.checkBox_yz_image.setObjectName(u"checkBox_yz_image")
        self.checkBox_yz_image.setGeometry(QRect(270, 130, 21, 21))
        self.horizontalSlider_yz = QSlider(self.tab_slice)
        self.horizontalSlider_yz.setObjectName(u"horizontalSlider_yz")
        self.horizontalSlider_yz.setGeometry(QRect(20, 170, 181, 21))
        self.horizontalSlider_yz.setOrientation(Qt.Horizontal)
        self.label_yz = QLabel(self.tab_slice)
        self.label_yz.setObjectName(u"label_yz")
        self.label_yz.setGeometry(QRect(10, 130, 61, 21))
        self.horizontalSlider_xz = QSlider(self.tab_slice)
        self.horizontalSlider_xz.setObjectName(u"horizontalSlider_xz")
        self.horizontalSlider_xz.setGeometry(QRect(20, 260, 181, 21))
        self.horizontalSlider_xz.setOrientation(Qt.Horizontal)
        self.checkBox_xz_image = QCheckBox(self.tab_slice)
        self.checkBox_xz_image.setObjectName(u"checkBox_xz_image")
        self.checkBox_xz_image.setGeometry(QRect(270, 220, 21, 21))
        self.label_xz_maxValue = QLabel(self.tab_slice)
        self.label_xz_maxValue.setObjectName(u"label_xz_maxValue")
        self.label_xz_maxValue.setGeometry(QRect(160, 240, 61, 21))
        self.label_xz = QLabel(self.tab_slice)
        self.label_xz.setObjectName(u"label_xz")
        self.label_xz.setGeometry(QRect(10, 220, 61, 21))
        self.checkBox_xz_contour = QCheckBox(self.tab_slice)
        self.checkBox_xz_contour.setObjectName(u"checkBox_xz_contour")
        self.checkBox_xz_contour.setGeometry(QRect(220, 220, 21, 21))
        self.label_xz_minValue = QLabel(self.tab_slice)
        self.label_xz_minValue.setObjectName(u"label_xz_minValue")
        self.label_xz_minValue.setGeometry(QRect(10, 240, 61, 21))
        self.lineEdit_xyPlane = QLineEdit(self.tab_slice)
        self.lineEdit_xyPlane.setObjectName(u"lineEdit_xyPlane")
        self.lineEdit_xyPlane.setGeometry(QRect(90, 40, 111, 21))
        self.lineEdit_yzPlane = QLineEdit(self.tab_slice)
        self.lineEdit_yzPlane.setObjectName(u"lineEdit_yzPlane")
        self.lineEdit_yzPlane.setGeometry(QRect(90, 130, 111, 21))
        self.lineEdit_xzPlane = QLineEdit(self.tab_slice)
        self.lineEdit_xzPlane.setObjectName(u"lineEdit_xzPlane")
        self.lineEdit_xzPlane.setGeometry(QRect(90, 220, 111, 21))
        icon = QIcon()
        iconThemeName = u"accessories-text-editor"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)

        self.tabWidget.addTab(self.tab_slice, icon, "")
        self.tab_color = QWidget()
        self.tab_color.setObjectName(u"tab_color")
        self.label_colorSetting = QLabel(self.tab_color)
        self.label_colorSetting.setObjectName(u"label_colorSetting")
        self.label_colorSetting.setGeometry(QRect(10, 10, 131, 21))
        self.label_color_minValue_head = QLabel(self.tab_color)
        self.label_color_minValue_head.setObjectName(u"label_color_minValue_head")
        self.label_color_minValue_head.setGeometry(QRect(10, 40, 71, 21))
        self.label_color_maxValue_head = QLabel(self.tab_color)
        self.label_color_maxValue_head.setObjectName(u"label_color_maxValue_head")
        self.label_color_maxValue_head.setGeometry(QRect(10, 70, 71, 21))
        self.lineEdit_color_minValue = QLineEdit(self.tab_color)
        self.lineEdit_color_minValue.setObjectName(u"lineEdit_color_minValue")
        self.lineEdit_color_minValue.setGeometry(QRect(90, 40, 161, 21))
        self.lineEdit_color_maxValue = QLineEdit(self.tab_color)
        self.lineEdit_color_maxValue.setObjectName(u"lineEdit_color_maxValue")
        self.lineEdit_color_maxValue.setGeometry(QRect(90, 70, 161, 21))
        self.pushButton_color_reset = QPushButton(self.tab_color)
        self.pushButton_color_reset.setObjectName(u"pushButton_color_reset")
        self.pushButton_color_reset.setGeometry(QRect(10, 100, 81, 31))
        self.tabWidget.addTab(self.tab_color, "")
        self.tab_isosurface = QWidget()
        self.tab_isosurface.setObjectName(u"tab_isosurface")
        self.label_isosurface1 = QLabel(self.tab_isosurface)
        self.label_isosurface1.setObjectName(u"label_isosurface1")
        self.label_isosurface1.setGeometry(QRect(10, 10, 81, 16))
        self.checkBox_isosurface1_mesh = QCheckBox(self.tab_isosurface)
        self.checkBox_isosurface1_mesh.setObjectName(u"checkBox_isosurface1_mesh")
        self.checkBox_isosurface1_mesh.setGeometry(QRect(130, 10, 75, 20))
        self.label_isosurface1_value = QLabel(self.tab_isosurface)
        self.label_isosurface1_value.setObjectName(u"label_isosurface1_value")
        self.label_isosurface1_value.setGeometry(QRect(10, 30, 49, 21))
        self.label_isosurface1_minValue = QLabel(self.tab_isosurface)
        self.label_isosurface1_minValue.setObjectName(u"label_isosurface1_minValue")
        self.label_isosurface1_minValue.setGeometry(QRect(10, 50, 61, 21))
        self.label_isosurface1_maxValue = QLabel(self.tab_isosurface)
        self.label_isosurface1_maxValue.setObjectName(u"label_isosurface1_maxValue")
        self.label_isosurface1_maxValue.setGeometry(QRect(170, 50, 61, 21))
        self.horizontalSlider_isosurface1 = QSlider(self.tab_isosurface)
        self.horizontalSlider_isosurface1.setObjectName(u"horizontalSlider_isosurface1")
        self.horizontalSlider_isosurface1.setGeometry(QRect(20, 70, 191, 20))
        self.horizontalSlider_isosurface1.setOrientation(Qt.Horizontal)
        self.comboBox_isosurface1_color = QComboBox(self.tab_isosurface)
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.addItem("")
        self.comboBox_isosurface1_color.setObjectName(u"comboBox_isosurface1_color")
        self.comboBox_isosurface1_color.setGeometry(QRect(190, 20, 91, 22))
        self.checkBox_isosurface2_mesh = QCheckBox(self.tab_isosurface)
        self.checkBox_isosurface2_mesh.setObjectName(u"checkBox_isosurface2_mesh")
        self.checkBox_isosurface2_mesh.setGeometry(QRect(130, 129, 75, 21))
        self.comboBox_isosurface2_color = QComboBox(self.tab_isosurface)
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.addItem("")
        self.comboBox_isosurface2_color.setObjectName(u"comboBox_isosurface2_color")
        self.comboBox_isosurface2_color.setGeometry(QRect(190, 140, 91, 22))
        self.label_isosurface2_minValue = QLabel(self.tab_isosurface)
        self.label_isosurface2_minValue.setObjectName(u"label_isosurface2_minValue")
        self.label_isosurface2_minValue.setGeometry(QRect(10, 170, 61, 21))
        self.label_isosurface2_maxValue = QLabel(self.tab_isosurface)
        self.label_isosurface2_maxValue.setObjectName(u"label_isosurface2_maxValue")
        self.label_isosurface2_maxValue.setGeometry(QRect(170, 170, 61, 21))
        self.label_isosurface2_value = QLabel(self.tab_isosurface)
        self.label_isosurface2_value.setObjectName(u"label_isosurface2_value")
        self.label_isosurface2_value.setGeometry(QRect(10, 150, 49, 21))
        self.label_isosurface2 = QLabel(self.tab_isosurface)
        self.label_isosurface2.setObjectName(u"label_isosurface2")
        self.label_isosurface2.setGeometry(QRect(10, 125, 81, 21))
        self.horizontalSlider_isosurface2 = QSlider(self.tab_isosurface)
        self.horizontalSlider_isosurface2.setObjectName(u"horizontalSlider_isosurface2")
        self.horizontalSlider_isosurface2.setGeometry(QRect(20, 190, 191, 20))
        self.horizontalSlider_isosurface2.setOrientation(Qt.Horizontal)
        self.lineEdit_isosurface1 = QLineEdit(self.tab_isosurface)
        self.lineEdit_isosurface1.setObjectName(u"lineEdit_isosurface1")
        self.lineEdit_isosurface1.setGeometry(QRect(60, 30, 121, 21))
        self.lineEdit_isosurface2 = QLineEdit(self.tab_isosurface)
        self.lineEdit_isosurface2.setObjectName(u"lineEdit_isosurface2")
        self.lineEdit_isosurface2.setGeometry(QRect(60, 150, 121, 21))
        self.tabWidget.addTab(self.tab_isosurface, "")
        self.tab_vector = QWidget()
        self.tab_vector.setObjectName(u"tab_vector")
        self.checkBox_vector_mag = QCheckBox(self.tab_vector)
        self.checkBox_vector_mag.setObjectName(u"checkBox_vector_mag")
        self.checkBox_vector_mag.setGeometry(QRect(10, 10, 171, 21))
        self.label_vector_mag_x_head = QLabel(self.tab_vector)
        self.label_vector_mag_x_head.setObjectName(u"label_vector_mag_x_head")
        self.label_vector_mag_x_head.setGeometry(QRect(10, 30, 21, 21))
        self.label_vector_mag_x = QLabel(self.tab_vector)
        self.label_vector_mag_x.setObjectName(u"label_vector_mag_x")
        self.label_vector_mag_x.setGeometry(QRect(30, 30, 81, 21))
        self.label_vector_mag_y = QLabel(self.tab_vector)
        self.label_vector_mag_y.setObjectName(u"label_vector_mag_y")
        self.label_vector_mag_y.setGeometry(QRect(130, 30, 81, 21))
        self.label_vector_mag_y_head = QLabel(self.tab_vector)
        self.label_vector_mag_y_head.setObjectName(u"label_vector_mag_y_head")
        self.label_vector_mag_y_head.setGeometry(QRect(110, 30, 21, 21))
        self.label_vector_mag_z_head = QLabel(self.tab_vector)
        self.label_vector_mag_z_head.setObjectName(u"label_vector_mag_z_head")
        self.label_vector_mag_z_head.setGeometry(QRect(210, 30, 21, 21))
        self.label_vector_mag_z = QLabel(self.tab_vector)
        self.label_vector_mag_z.setObjectName(u"label_vector_mag_z")
        self.label_vector_mag_z.setGeometry(QRect(230, 30, 81, 21))
        self.comboBox_vector_mag_scale = QComboBox(self.tab_vector)
        self.comboBox_vector_mag_scale.addItem("")
        self.comboBox_vector_mag_scale.addItem("")
        self.comboBox_vector_mag_scale.addItem("")
        self.comboBox_vector_mag_scale.setObjectName(u"comboBox_vector_mag_scale")
        self.comboBox_vector_mag_scale.setGeometry(QRect(80, 50, 68, 22))
        self.comboBox_vector_mag_thick = QComboBox(self.tab_vector)
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.addItem("")
        self.comboBox_vector_mag_thick.setObjectName(u"comboBox_vector_mag_thick")
        self.comboBox_vector_mag_thick.setGeometry(QRect(150, 50, 68, 22))
        self.comboBox_vector_mag_color = QComboBox(self.tab_vector)
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.addItem("")
        self.comboBox_vector_mag_color.setObjectName(u"comboBox_vector_mag_color")
        self.comboBox_vector_mag_color.setGeometry(QRect(10, 50, 68, 22))
        self.comboBox_vector_vel_scale = QComboBox(self.tab_vector)
        self.comboBox_vector_vel_scale.addItem("")
        self.comboBox_vector_vel_scale.addItem("")
        self.comboBox_vector_vel_scale.addItem("")
        self.comboBox_vector_vel_scale.setObjectName(u"comboBox_vector_vel_scale")
        self.comboBox_vector_vel_scale.setGeometry(QRect(80, 130, 68, 22))
        self.label_vector_vel_z = QLabel(self.tab_vector)
        self.label_vector_vel_z.setObjectName(u"label_vector_vel_z")
        self.label_vector_vel_z.setGeometry(QRect(230, 110, 81, 21))
        self.checkBox_vector_vel = QCheckBox(self.tab_vector)
        self.checkBox_vector_vel.setObjectName(u"checkBox_vector_vel")
        self.checkBox_vector_vel.setGeometry(QRect(10, 90, 161, 21))
        self.comboBox_vector_vel_thick = QComboBox(self.tab_vector)
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.addItem("")
        self.comboBox_vector_vel_thick.setObjectName(u"comboBox_vector_vel_thick")
        self.comboBox_vector_vel_thick.setGeometry(QRect(150, 130, 68, 22))
        self.label_vector_vel_x_head = QLabel(self.tab_vector)
        self.label_vector_vel_x_head.setObjectName(u"label_vector_vel_x_head")
        self.label_vector_vel_x_head.setGeometry(QRect(10, 110, 21, 21))
        self.label_vector_vel_z_head = QLabel(self.tab_vector)
        self.label_vector_vel_z_head.setObjectName(u"label_vector_vel_z_head")
        self.label_vector_vel_z_head.setGeometry(QRect(210, 110, 21, 21))
        self.label_vector_vel_y_head = QLabel(self.tab_vector)
        self.label_vector_vel_y_head.setObjectName(u"label_vector_vel_y_head")
        self.label_vector_vel_y_head.setGeometry(QRect(110, 110, 21, 21))
        self.comboBox_vector_vel_color = QComboBox(self.tab_vector)
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.addItem("")
        self.comboBox_vector_vel_color.setObjectName(u"comboBox_vector_vel_color")
        self.comboBox_vector_vel_color.setGeometry(QRect(10, 130, 68, 22))
        self.label_vector_vel_x = QLabel(self.tab_vector)
        self.label_vector_vel_x.setObjectName(u"label_vector_vel_x")
        self.label_vector_vel_x.setGeometry(QRect(30, 110, 81, 21))
        self.label_vector_vel_y = QLabel(self.tab_vector)
        self.label_vector_vel_y.setObjectName(u"label_vector_vel_y")
        self.label_vector_vel_y.setGeometry(QRect(130, 110, 81, 21))
        self.checkBox_vector_user = QCheckBox(self.tab_vector)
        self.checkBox_vector_user.setObjectName(u"checkBox_vector_user")
        self.checkBox_vector_user.setGeometry(QRect(10, 180, 161, 21))
        self.comboBox_vector_user_thick = QComboBox(self.tab_vector)
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.addItem("")
        self.comboBox_vector_user_thick.setObjectName(u"comboBox_vector_user_thick")
        self.comboBox_vector_user_thick.setGeometry(QRect(150, 230, 68, 22))
        self.label_vector_user_x_head = QLabel(self.tab_vector)
        self.label_vector_user_x_head.setObjectName(u"label_vector_user_x_head")
        self.label_vector_user_x_head.setGeometry(QRect(10, 200, 21, 21))
        self.label_vector_user_z_head = QLabel(self.tab_vector)
        self.label_vector_user_z_head.setObjectName(u"label_vector_user_z_head")
        self.label_vector_user_z_head.setGeometry(QRect(210, 200, 21, 21))
        self.comboBox_vector_user_scale = QComboBox(self.tab_vector)
        self.comboBox_vector_user_scale.addItem("")
        self.comboBox_vector_user_scale.addItem("")
        self.comboBox_vector_user_scale.addItem("")
        self.comboBox_vector_user_scale.setObjectName(u"comboBox_vector_user_scale")
        self.comboBox_vector_user_scale.setGeometry(QRect(80, 230, 68, 22))
        self.label_vector_user_y_head = QLabel(self.tab_vector)
        self.label_vector_user_y_head.setObjectName(u"label_vector_user_y_head")
        self.label_vector_user_y_head.setGeometry(QRect(110, 200, 21, 21))
        self.comboBox_vector_user_color = QComboBox(self.tab_vector)
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.addItem("")
        self.comboBox_vector_user_color.setObjectName(u"comboBox_vector_user_color")
        self.comboBox_vector_user_color.setGeometry(QRect(10, 230, 68, 22))
        self.lineEdit_vector_user_x = QLineEdit(self.tab_vector)
        self.lineEdit_vector_user_x.setObjectName(u"lineEdit_vector_user_x")
        self.lineEdit_vector_user_x.setGeometry(QRect(20, 200, 81, 21))
        self.lineEdit_vector_user_y = QLineEdit(self.tab_vector)
        self.lineEdit_vector_user_y.setObjectName(u"lineEdit_vector_user_y")
        self.lineEdit_vector_user_y.setGeometry(QRect(120, 200, 81, 21))
        self.lineEdit_vector_user_z = QLineEdit(self.tab_vector)
        self.lineEdit_vector_user_z.setObjectName(u"lineEdit_vector_user_z")
        self.lineEdit_vector_user_z.setGeometry(QRect(220, 200, 81, 21))
        self.tabWidget.addTab(self.tab_vector, "")
        self.tab_view = QWidget()
        self.tab_view.setObjectName(u"tab_view")
        self.pushButton_view_reset = QPushButton(self.tab_view)
        self.pushButton_view_reset.setObjectName(u"pushButton_view_reset")
        self.pushButton_view_reset.setGeometry(QRect(10, 150, 81, 31))
        self.label = QLabel(self.tab_view)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 141, 21))
        self.checkBox_view_axis = QCheckBox(self.tab_view)
        self.checkBox_view_axis.setObjectName(u"checkBox_view_axis")
        self.checkBox_view_axis.setGeometry(QRect(150, 30, 61, 21))
        self.checkBox_view_center = QCheckBox(self.tab_view)
        self.checkBox_view_center.setObjectName(u"checkBox_view_center")
        self.checkBox_view_center.setGeometry(QRect(70, 30, 71, 21))
        self.checkBox_view_box = QCheckBox(self.tab_view)
        self.checkBox_view_box.setObjectName(u"checkBox_view_box")
        self.checkBox_view_box.setGeometry(QRect(10, 30, 61, 21))
        self.label_2 = QLabel(self.tab_view)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 81, 16))
        self.pushButton_view_xzPlane = QPushButton(self.tab_view)
        self.pushButton_view_xzPlane.setObjectName(u"pushButton_view_xzPlane")
        self.pushButton_view_xzPlane.setGeometry(QRect(190, 90, 81, 31))
        self.pushButton_view_xyPlane = QPushButton(self.tab_view)
        self.pushButton_view_xyPlane.setObjectName(u"pushButton_view_xyPlane")
        self.pushButton_view_xyPlane.setGeometry(QRect(10, 90, 81, 31))
        self.pushButton_view_yzPlane = QPushButton(self.tab_view)
        self.pushButton_view_yzPlane.setObjectName(u"pushButton_view_yzPlane")
        self.pushButton_view_yzPlane.setGeometry(QRect(100, 90, 81, 31))
        self.tabWidget.addTab(self.tab_view, "")

        self.verticalLayout_2.addWidget(self.widget)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.horizontalLayout.addWidget(self.scrollArea)

        self.verticalLayout_viewer = QVBoxLayout()
        self.verticalLayout_viewer.setObjectName(u"verticalLayout_viewer")
        self.verticalLayout_viewer.setSizeConstraint(QLayout.SetNoConstraint)
        self.label_data = QLabel(self.centralwidget)
        self.label_data.setObjectName(u"label_data")
        font3 = QFont()
        font3.setPointSize(16)
        self.label_data.setFont(font3)
        self.label_data.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)

        self.verticalLayout_viewer.addWidget(self.label_data)


        self.horizontalLayout.addLayout(self.verticalLayout_viewer)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setFont(font2)
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.checkBox_xy_image.stateChanged.connect(MainWindow.change_show_xyPlane_image)
        self.lineEdit_isosurface2.editingFinished.connect(MainWindow.change_isosurface2_value_text)
        self.lineEdit_color_minValue.editingFinished.connect(MainWindow.edit_color_values)
        self.comboBox_vector_vel_thick.currentTextChanged.connect(MainWindow.change_vector_vel_thick)
        self.lineEdit_xyPlane.editingFinished.connect(MainWindow.edit_xyPlane_value_text)
        self.lineEdit_vector_user_y.editingFinished.connect(MainWindow.change_vector_user_elems)
        self.lineEdit_vector_user_z.editingFinished.connect(MainWindow.change_vector_user_elems)
        self.checkBox_xy_contour.stateChanged.connect(MainWindow.change_show_xyPlane_contour)
        self.comboBox_isosurface2_color.currentTextChanged.connect(MainWindow.change_isosurface2_color)
        self.comboBox_vector_mag_color.currentTextChanged.connect(MainWindow.change_vector_mag_color)
        self.lineEdit_vector_user_x.editingFinished.connect(MainWindow.change_vector_user_elems)
        self.comboBox_vector_mag_scale.currentTextChanged.connect(MainWindow.change_vector_mag_scale)
        self.pushButton_view_xyPlane.clicked.connect(MainWindow.view_xyPlane)
        self.comboBox_vector_mag_thick.currentTextChanged.connect(MainWindow.change_vector_mag_thick)
        self.horizontalSlider_isosurface2.valueChanged.connect(MainWindow.change_isosurface2_value_slider)
        self.comboBox_vector_vel_scale.currentTextChanged.connect(MainWindow.change_vector_vel_scale)
        self.checkBox_xz_contour.stateChanged.connect(MainWindow.change_show_xzPlane_contour)
        self.comboBox_isosurface1_color.currentTextChanged.connect(MainWindow.change_isosurface1_color)
        self.checkBox_vector_user.stateChanged.connect(MainWindow.change_show_vector_user)
        self.horizontalSlider_xz.valueChanged.connect(MainWindow.change_xzPlane_value_slider)
        self.comboBox_vector_user_thick.currentTextChanged.connect(MainWindow.change_vector_user_thick)
        self.checkBox_yz_image.stateChanged.connect(MainWindow.change_show_yzPlane_image)
        self.checkBox_vector_mag.stateChanged.connect(MainWindow.change_show_vector_mag)
        self.comboBox_vector_vel_color.currentTextChanged.connect(MainWindow.change_vector_vel_color)
        self.horizontalSlider_yz.valueChanged.connect(MainWindow.change_yzPlane_value_slider)
        self.horizontalSlider_isosurface1.valueChanged.connect(MainWindow.change_isosurface1_value_slider)
        self.checkBox_yz_contour.stateChanged.connect(MainWindow.change_show_yzPlane_contour)
        self.checkBox_vector_vel.stateChanged.connect(MainWindow.change_show_vector_vel)
        self.checkBox_isosurface2_mesh.stateChanged.connect(MainWindow.change_isosurface2_mesh)
        self.lineEdit_xzPlane.editingFinished.connect(MainWindow.edit_xzPlane_value_text)
        self.comboBox_vector_user_color.currentTextChanged.connect(MainWindow.change_vector_user_color)
        self.lineEdit_isosurface1.editingFinished.connect(MainWindow.change_isosurface1_value_text)
        self.checkBox_xz_image.stateChanged.connect(MainWindow.change_show_xzPlane_image)
        self.pushButton_view_reset.clicked.connect(MainWindow.view_reset)
        self.pushButton_view_xzPlane.clicked.connect(MainWindow.view_xzPlane)
        self.checkBox_isosurface1_mesh.stateChanged.connect(MainWindow.change_isosurface1_mesh)
        self.lineEdit_yzPlane.editingFinished.connect(MainWindow.edit_yzPlane_value_text)
        self.comboBox_vector_user_scale.currentTextChanged.connect(MainWindow.change_vector_user_scale)
        self.pushButton_view_yzPlane.clicked.connect(MainWindow.view_yzPlane)
        self.lineEdit_color_maxValue.editingFinished.connect(MainWindow.edit_color_values)
        self.horizontalSlider_xy.valueChanged.connect(MainWindow.change_xyPlane_value_slider)
        self.checkBox_view_center.stateChanged.connect(MainWindow.change_view_center)
        self.checkBox_view_box.stateChanged.connect(MainWindow.change_view_box)
        self.checkBox_view_axis.stateChanged.connect(MainWindow.change_view_axis)
        self.checkBox_isosurface1.stateChanged.connect(MainWindow.change_show_isosurface1)
        self.checkBox_isosurface2.stateChanged.connect(MainWindow.change_show_isosurface2)
        self.pushButton_saveImage.clicked.connect(MainWindow.click_save_button)
        self.comboBox_coordinates.currentTextChanged.connect(MainWindow.change_coordinates)
        self.comboBox_axisUnits.currentTextChanged.connect(MainWindow.change_axisUnits)
        self.comboBox_units.currentTextChanged.connect(MainWindow.change_units)
        self.horizontalSlider_dataStartTime.valueChanged.connect(MainWindow.change_data)
        self.pushButton_color_reset.clicked.connect(MainWindow.color_reset)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ISEE_3D", None))
        self.checkBox_isosurface1.setText(QCoreApplication.translate("MainWindow", u"Isosurface1", None))
        self.checkBox_isosurface2.setText(QCoreApplication.translate("MainWindow", u"Isosurface2", None))
        self.label_types.setText(QCoreApplication.translate("MainWindow", u"Types", None))
        self.comboBox_saveType.setItemText(0, QCoreApplication.translate("MainWindow", u"PNG", None))
        self.comboBox_saveType.setItemText(1, QCoreApplication.translate("MainWindow", u"EPS", None))

        self.pushButton_saveImage.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.label_coordinates.setText(QCoreApplication.translate("MainWindow", u"Coordinates", None))
        self.comboBox_coordinates.setItemText(0, QCoreApplication.translate("MainWindow", u"SC", None))
        self.comboBox_coordinates.setItemText(1, QCoreApplication.translate("MainWindow", u"MAG", None))

        self.label_axisUnits.setText(QCoreApplication.translate("MainWindow", u"Axis Units", None))
        self.comboBox_axisUnits.setItemText(0, QCoreApplication.translate("MainWindow", u"Velocity", None))
        self.comboBox_axisUnits.setItemText(1, QCoreApplication.translate("MainWindow", u"Energy", None))

        self.label_units.setText(QCoreApplication.translate("MainWindow", u"Units", None))
        self.comboBox_units.setItemText(0, QCoreApplication.translate("MainWindow", u"PSD", None))
        self.comboBox_units.setItemText(1, QCoreApplication.translate("MainWindow", u"FLUX", None))

        self.label_firstTime_slider.setText(QCoreApplication.translate("MainWindow", u"HH:MM:SS.fff", None))
        self.label_lastTime_slider.setText(QCoreApplication.translate("MainWindow", u"HH:MM:SS.fff", None))
        self.label_startTime_head.setText(QCoreApplication.translate("MainWindow", u"Start Time(UT)", None))
        self.label_endTime_head.setText(QCoreApplication.translate("MainWindow", u"End Time(UT)", None))
        self.label_startTime.setText(QCoreApplication.translate("MainWindow", u"yyyy-mm-dd/HH:MM:SS.fff", None))
        self.label_endTime.setText(QCoreApplication.translate("MainWindow", u"yyyy-mm-dd/HH:MM:SS.fff", None))
        self.label_xy.setText(QCoreApplication.translate("MainWindow", u"XY-Plane", None))
        self.label_slice.setText(QCoreApplication.translate("MainWindow", u"Slice 2D", None))
        self.checkBox_xy_contour.setText("")
        self.checkBox_xy_image.setText("")
        self.label_contour.setText(QCoreApplication.translate("MainWindow", u"Contour", None))
        self.label_image.setText(QCoreApplication.translate("MainWindow", u"Image", None))
        self.label_xy_minValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.label_xy_maxValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.checkBox_yz_contour.setText("")
        self.label_yz_minValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.label_yz_maxValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.checkBox_yz_image.setText("")
        self.label_yz.setText(QCoreApplication.translate("MainWindow", u"YZ-Plane", None))
        self.checkBox_xz_image.setText("")
        self.label_xz_maxValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.label_xz.setText(QCoreApplication.translate("MainWindow", u"XZ-Plane", None))
        self.checkBox_xz_contour.setText("")
        self.label_xz_minValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_slice), QCoreApplication.translate("MainWindow", u"Slice", None))
        self.label_colorSetting.setText(QCoreApplication.translate("MainWindow", u"Display Color Setting", None))
        self.label_color_minValue_head.setText(QCoreApplication.translate("MainWindow", u"Min Value", None))
        self.label_color_maxValue_head.setText(QCoreApplication.translate("MainWindow", u"Max Value", None))
        self.pushButton_color_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_color), QCoreApplication.translate("MainWindow", u"Color", None))
        self.label_isosurface1.setText(QCoreApplication.translate("MainWindow", u"Isosurface1", None))
        self.checkBox_isosurface1_mesh.setText(QCoreApplication.translate("MainWindow", u"Mesh", None))
        self.label_isosurface1_value.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.label_isosurface1_minValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.label_isosurface1_maxValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.comboBox_isosurface1_color.setItemText(0, QCoreApplication.translate("MainWindow", u"RED", None))
        self.comboBox_isosurface1_color.setItemText(1, QCoreApplication.translate("MainWindow", u"BLUE", None))
        self.comboBox_isosurface1_color.setItemText(2, QCoreApplication.translate("MainWindow", u"GREEN", None))
        self.comboBox_isosurface1_color.setItemText(3, QCoreApplication.translate("MainWindow", u"LIME", None))
        self.comboBox_isosurface1_color.setItemText(4, QCoreApplication.translate("MainWindow", u"YELLOW", None))
        self.comboBox_isosurface1_color.setItemText(5, QCoreApplication.translate("MainWindow", u"MAGENTA", None))
        self.comboBox_isosurface1_color.setItemText(6, QCoreApplication.translate("MainWindow", u"CYAN", None))
        self.comboBox_isosurface1_color.setItemText(7, QCoreApplication.translate("MainWindow", u"WHITE", None))
        self.comboBox_isosurface1_color.setItemText(8, QCoreApplication.translate("MainWindow", u"BLACK", None))

        self.checkBox_isosurface2_mesh.setText(QCoreApplication.translate("MainWindow", u"Mesh", None))
        self.comboBox_isosurface2_color.setItemText(0, QCoreApplication.translate("MainWindow", u"RED", None))
        self.comboBox_isosurface2_color.setItemText(1, QCoreApplication.translate("MainWindow", u"BLUE", None))
        self.comboBox_isosurface2_color.setItemText(2, QCoreApplication.translate("MainWindow", u"GREEN", None))
        self.comboBox_isosurface2_color.setItemText(3, QCoreApplication.translate("MainWindow", u"LIME", None))
        self.comboBox_isosurface2_color.setItemText(4, QCoreApplication.translate("MainWindow", u"YELLOW", None))
        self.comboBox_isosurface2_color.setItemText(5, QCoreApplication.translate("MainWindow", u"MAGENTA", None))
        self.comboBox_isosurface2_color.setItemText(6, QCoreApplication.translate("MainWindow", u"CYAN", None))
        self.comboBox_isosurface2_color.setItemText(7, QCoreApplication.translate("MainWindow", u"WHITE", None))
        self.comboBox_isosurface2_color.setItemText(8, QCoreApplication.translate("MainWindow", u"BLACK", None))

        self.label_isosurface2_minValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.label_isosurface2_maxValue.setText(QCoreApplication.translate("MainWindow", u"-0.0e-00", None))
        self.label_isosurface2_value.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.label_isosurface2.setText(QCoreApplication.translate("MainWindow", u"Isosurface2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_isosurface), QCoreApplication.translate("MainWindow", u"Isosurface", None))
        self.checkBox_vector_mag.setText(QCoreApplication.translate("MainWindow", u"Magnetic field vector(nT)", None))
        self.label_vector_mag_x_head.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_vector_mag_x.setText(QCoreApplication.translate("MainWindow", u"x_value", None))
        self.label_vector_mag_y.setText(QCoreApplication.translate("MainWindow", u"y_value", None))
        self.label_vector_mag_y_head.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_vector_mag_z_head.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_vector_mag_z.setText(QCoreApplication.translate("MainWindow", u"z_value", None))
        self.comboBox_vector_mag_scale.setItemText(0, QCoreApplication.translate("MainWindow", u"full", None))
        self.comboBox_vector_mag_scale.setItemText(1, QCoreApplication.translate("MainWindow", u"half", None))
        self.comboBox_vector_mag_scale.setItemText(2, QCoreApplication.translate("MainWindow", u"quarter", None))

        self.comboBox_vector_mag_thick.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_vector_mag_thick.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_vector_mag_thick.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_vector_mag_thick.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_vector_mag_thick.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_vector_mag_thick.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_vector_mag_thick.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_vector_mag_thick.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_vector_mag_thick.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_vector_mag_thick.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))

        self.comboBox_vector_mag_color.setItemText(0, QCoreApplication.translate("MainWindow", u"RED", None))
        self.comboBox_vector_mag_color.setItemText(1, QCoreApplication.translate("MainWindow", u"BLUE", None))
        self.comboBox_vector_mag_color.setItemText(2, QCoreApplication.translate("MainWindow", u"GREEN", None))
        self.comboBox_vector_mag_color.setItemText(3, QCoreApplication.translate("MainWindow", u"LIME", None))
        self.comboBox_vector_mag_color.setItemText(4, QCoreApplication.translate("MainWindow", u"YELLOW", None))
        self.comboBox_vector_mag_color.setItemText(5, QCoreApplication.translate("MainWindow", u"MAGENTA", None))
        self.comboBox_vector_mag_color.setItemText(6, QCoreApplication.translate("MainWindow", u"CYAN", None))
        self.comboBox_vector_mag_color.setItemText(7, QCoreApplication.translate("MainWindow", u"WHITE", None))
        self.comboBox_vector_mag_color.setItemText(8, QCoreApplication.translate("MainWindow", u"BLACK", None))

        self.comboBox_vector_vel_scale.setItemText(0, QCoreApplication.translate("MainWindow", u"full", None))
        self.comboBox_vector_vel_scale.setItemText(1, QCoreApplication.translate("MainWindow", u"half", None))
        self.comboBox_vector_vel_scale.setItemText(2, QCoreApplication.translate("MainWindow", u"quarter", None))

        self.label_vector_vel_z.setText(QCoreApplication.translate("MainWindow", u"z_value", None))
        self.checkBox_vector_vel.setText(QCoreApplication.translate("MainWindow", u"Velocity vector(km/s)", None))
        self.comboBox_vector_vel_thick.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_vector_vel_thick.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_vector_vel_thick.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_vector_vel_thick.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_vector_vel_thick.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_vector_vel_thick.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_vector_vel_thick.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_vector_vel_thick.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_vector_vel_thick.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_vector_vel_thick.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))

        self.label_vector_vel_x_head.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_vector_vel_z_head.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.label_vector_vel_y_head.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.comboBox_vector_vel_color.setItemText(0, QCoreApplication.translate("MainWindow", u"RED", None))
        self.comboBox_vector_vel_color.setItemText(1, QCoreApplication.translate("MainWindow", u"BLUE", None))
        self.comboBox_vector_vel_color.setItemText(2, QCoreApplication.translate("MainWindow", u"GREEN", None))
        self.comboBox_vector_vel_color.setItemText(3, QCoreApplication.translate("MainWindow", u"LIME", None))
        self.comboBox_vector_vel_color.setItemText(4, QCoreApplication.translate("MainWindow", u"YELLOW", None))
        self.comboBox_vector_vel_color.setItemText(5, QCoreApplication.translate("MainWindow", u"MAGENTA", None))
        self.comboBox_vector_vel_color.setItemText(6, QCoreApplication.translate("MainWindow", u"CYAN", None))
        self.comboBox_vector_vel_color.setItemText(7, QCoreApplication.translate("MainWindow", u"WHITE", None))
        self.comboBox_vector_vel_color.setItemText(8, QCoreApplication.translate("MainWindow", u"BLACK", None))

        self.label_vector_vel_x.setText(QCoreApplication.translate("MainWindow", u"x_value", None))
        self.label_vector_vel_y.setText(QCoreApplication.translate("MainWindow", u"y_value", None))
        self.checkBox_vector_user.setText(QCoreApplication.translate("MainWindow", u"User vector", None))
        self.comboBox_vector_user_thick.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_vector_user_thick.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_vector_user_thick.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_vector_user_thick.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_vector_user_thick.setItemText(4, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_vector_user_thick.setItemText(5, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_vector_user_thick.setItemText(6, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_vector_user_thick.setItemText(7, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_vector_user_thick.setItemText(8, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_vector_user_thick.setItemText(9, QCoreApplication.translate("MainWindow", u"10", None))

        self.label_vector_user_x_head.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_vector_user_z_head.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.comboBox_vector_user_scale.setItemText(0, QCoreApplication.translate("MainWindow", u"full", None))
        self.comboBox_vector_user_scale.setItemText(1, QCoreApplication.translate("MainWindow", u"half", None))
        self.comboBox_vector_user_scale.setItemText(2, QCoreApplication.translate("MainWindow", u"quarter", None))

        self.label_vector_user_y_head.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.comboBox_vector_user_color.setItemText(0, QCoreApplication.translate("MainWindow", u"RED", None))
        self.comboBox_vector_user_color.setItemText(1, QCoreApplication.translate("MainWindow", u"BLUE", None))
        self.comboBox_vector_user_color.setItemText(2, QCoreApplication.translate("MainWindow", u"GREEN", None))
        self.comboBox_vector_user_color.setItemText(3, QCoreApplication.translate("MainWindow", u"LIME", None))
        self.comboBox_vector_user_color.setItemText(4, QCoreApplication.translate("MainWindow", u"YELLOW", None))
        self.comboBox_vector_user_color.setItemText(5, QCoreApplication.translate("MainWindow", u"MAGENTA", None))
        self.comboBox_vector_user_color.setItemText(6, QCoreApplication.translate("MainWindow", u"CYAN", None))
        self.comboBox_vector_user_color.setItemText(7, QCoreApplication.translate("MainWindow", u"WHITE", None))
        self.comboBox_vector_user_color.setItemText(8, QCoreApplication.translate("MainWindow", u"BLACK", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vector), QCoreApplication.translate("MainWindow", u"Vector", None))
        self.pushButton_view_reset.setText(QCoreApplication.translate("MainWindow", u"Reset View", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Turn On/Off Axis and Box", None))
        self.checkBox_view_axis.setText(QCoreApplication.translate("MainWindow", u"Axis", None))
        self.checkBox_view_center.setText(QCoreApplication.translate("MainWindow", u"Center", None))
        self.checkBox_view_box.setText(QCoreApplication.translate("MainWindow", u"Box", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Plane View", None))
        self.pushButton_view_xzPlane.setText(QCoreApplication.translate("MainWindow", u"XZ-Plane", None))
        self.pushButton_view_xyPlane.setText(QCoreApplication.translate("MainWindow", u"XY-Plane", None))
        self.pushButton_view_yzPlane.setText(QCoreApplication.translate("MainWindow", u"YZ-Plane", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_view), QCoreApplication.translate("MainWindow", u"View", None))
        self.label_data.setText(QCoreApplication.translate("MainWindow", u"yyyy-mm-dd/HH:MM:SS.fff - yyyy-mm-dd/HH:MM:SS.fff  (axis units)", None))
    # retranslateUi

